### ISSUE TITLE
Mockup basic front-end using Bulma

### ISSUE THREAD

**Issue by nobleburgundy** [nobleburgundy/weather-jamz#13]
Using Bulma - create the basic HTML for the application. 

Welcome page/modal/jumbotron (depending on design)
City Search Input
Song List to put the results of the search

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/98270612-a91e9600-1f54-11eb-96b7-e5a8b8b1e4d0.png)
1st draft

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/98302550-362c1400-1f82-11eb-90c2-dfede97dc462.png)

**Comment by klyngdal** [comment]
looks great!

**Comment by nobleburgundy** [comment]
Nice - I like the colorful one!
