### ISSUE TITLE
change opacity 

### ISSUE THREAD

**Issue by klyngdal** [nobleburgundy/weather-jamz#33]
maybe look at css 14-15

what are the opinions on the color scheme with the opacity change ??

**Comment by Kay0s** [comment]
background-color: rgba(0, 0, 0, 0.8);  --- for opacity its the "0.8" on the end that makes that change just fyi!

**Comment by Kay0s** [comment]
Kelsey and I worked on the opacity for the song list container and searched city container.  What are people's thoughts?

**Comment by nobleburgundy** [comment]
@klyngdal @Kay0s - I added a comment to this pr...
https://github.com/nobleburgundy/weather-jamz/pull/44
Is that where this question is referring to?

Also, I just noticed we can link pull requests to issues on the right. I linked this one - if it's wrong, feel free to remove the link.
