### ISSUE TITLE
Back end - hook up search input

### ISSUE THREAD

**Issue by alimariam12** [nobleburgundy/weather-jamz#34]
Hook up to search input

**Comment by nobleburgundy** [comment]
Can do this once #35 is complete

**Comment by Meechlouch** [comment]
Event add listener added and a slight mod of the variable naming convention. Displaying Weather data to page is still in progress.

**Comment by Meechlouch** [comment]
Weather data is rendered though minor tweaks are needed. As of current, weather data creates multiples at every click of the search button.
