### ISSUE TITLE
Front End - Search Input

### ISSUE THREAD

**Issue by alimariam12** [nobleburgundy/weather-jamz#35]
Add input and search button 
Add id="citySearch" to input tag
Add id="searchBtn" to button tag

**Comment by Kay0s** [comment]
I'm working on adding the input for the searched city and the search button.

**Comment by Kay0s** [comment]
Added:
Added input and search button
Add id="citySearch" to input
Add id="searchBtn" to button

**Comment by Kay0s** [comment]
Kristina to do - add padding for the input section and search button.
