### ISSUE TITLE
Back End - Research YouTube Widget Playback Ability

### ISSUE THREAD

**Issue by alimariam12** [nobleburgundy/weather-jamz#36]
Back end research how to play the music from last.fm

**Comment by alimariam12** [comment]
working on it

**Comment by Kay0s** [comment]
James Gould - The way for us to play audio is to use YouTube's playlist functionality where we'll load the songs in via a youtube playlist - and that requires the use of their player widget.

**Comment by Kay0s** [comment]
Below is info about the YouTube Player.

https://developers.google.com/youtube/player_parameters#Overview

Is @nobleburgundy this what we should be looking into?

**Comment by nobleburgundy** [comment]
Research is completed, not implementing this in a different issue.
