### ISSUE TITLE
Front End - Layout for Youtube Player

### ISSUE THREAD

**Issue by alimariam12** [nobleburgundy/weather-jamz#38]
Creating a design picture for the play controls of the music lists.

**Comment by Kay0s** [comment]
Kristina is working on this.

**Comment by Kay0s** [comment]
What do we think about this for playback?  
 https://521dimensions.com/open-source/amplitudejs/docs/examples/blue-playlist.html

**Comment by Kay0s** [comment]
James Gould - The way for us to play audio is to use YouTube's playlist functionality where we'll load the songs in via a youtube playlist - and that requires the use of their player widget.

**Comment by Kay0s** [comment]
Below is info about the YouTube Player.

https://developers.google.com/youtube/player_parameters#Overview

Is @nobleburgundy this what we should be looking into?

**Comment by nobleburgundy** [comment]
@Kay0s - I started working this actually, but forgot to move to in progress. I think we can break this into 2 parts though. 1 to place the player on the page, and the other to generate the playlist via api. I'll create the playlist api task and assign to myself and this can be the front end portion. First though, let me get it added to index.html so the front-end team can work on sprucing it up.

**Comment by Kay0s** [comment]
Got it.  We'll work with what's added idex.html.

**Comment by Kay0s** [comment]
On the index.htm line 36, should the ul id="weather-music-list" be changed to a div with the id="playerId"?
This would eliminate the weather music list from appearing.
![image](https://user-images.githubusercontent.com/71153831/98754434-53028600-238c-11eb-846d-bd9a7a78bdaa.png)
![image](https://user-images.githubusercontent.com/71153831/98754508-7f1e0700-238c-11eb-990e-870871ea1c2a.png)
