### ISSUE TITLE
Create user flow

### ISSUE THREAD

**Issue by nobleburgundy** [nobleburgundy/weather-jamz#4]
Create the basic user flow diagram

**Comment by Kay0s** [comment]
User Flow Updated -
1.     User inputs their city location
2.     Open Weather API gets the current weather conditions and weather words. The app displays the weather icon to the user.
3.     SOUNDCLOUD API fetches tagged/ redetermined tags/genres to related to the weather.
4.     The App displays a songlist to the user.
