### ISSUE TITLE
Lets talk about color

### ISSUE THREAD

**Issue by klyngdal** [nobleburgundy/weather-jamz#45]
can every check out what I put together so far and lmk know your thoughts?

**Comment by randyWhitley** [comment]
James ,, I used Font Nexa— bold as text.. - Randy

**Comment by nobleburgundy** [comment]
@klyngdal - I like the color, but it seems a little too much transparency? With the background, seems a little busy. What about a value like "0.8" or "0.7" for the ```opacity```?

Is this issue for this pull request? 
https://github.com/nobleburgundy/weather-jamz/pull/44
