### ISSUE TITLE
Logo design and placement

### ISSUE THREAD

**Issue by nobleburgundy** [nobleburgundy/weather-jamz#46]
@randyWhitley - I really like the logos, but the 'Anemoi' word in the main logo is at the bottom and usually below the viewing screen. I think moving it up would make it too busy. What if we used the other logo...
https://github.com/nobleburgundy/weather-jamz/blob/development/anemoi1.png
at the top with an <h1>Anemoi</h1> and maybe the subtitle to show that logo with the title of the app in more of a navbar type component. 

Then, the keep the face logo in the middle as the background, but remove the words under that?  Just a thought. 

Any other opinions on that? This is a bad example, but something like Tidal's home page...
https://tidal.com/

**Comment by Kay0s** [comment]
https://files.slack.com/files-pri/T019YF39K5M-F01EUQ4ABEV/anemoi_edit1.jpg
randy moved anemoi name and music for any weather lower below the logo

**Comment by Kay0s** [comment]
Put logo in header to give room to YouTube Player.

**Comment by Kay0s** [comment]
https://files.slack.com/files-pri/T019YF39K5M-F01ED86GB8D/image.png
moved anemoi and logo to top of background image so cards will be below
