### ISSUE TITLE
previous city searched weather data not being removed

### ISSUE THREAD

**Issue by Meechlouch** [nobleburgundy/weather-jamz#53]
When you search for new city, the weather data from the previously searched city is still displaying. Should display just the current city search.

**Comment by alimariam12** [comment]
I was thinking we can have can have the history of the previously searched cities. Just like what we did in the assignment

**Comment by alimariam12** [comment]
I think we should only have the currently searched city.

**Comment by alimariam12** [comment]
I was able to fix that!
