### ISSUE TITLE
Bug - Anemoi icon missing

### ISSUE THREAD

**Issue by nobleburgundy** [nobleburgundy/weather-jamz#55]
We used to have the anemoi1 icon showing in the tab, but seems to be missing now. See screenshot...
![image](https://user-images.githubusercontent.com/1057230/98736333-4a00bd00-236a-11eb-8a0d-1aa41bae3e41.png)

**Comment by nobleburgundy** [comment]
![image](https://user-images.githubusercontent.com/1057230/98736302-40775500-236a-11eb-938f-1591d1a39a7a.png)

**Comment by Kay0s** [comment]
This will be added back in with my updates.

**Comment by Kay0s** [comment]
<link rel="icon" href="anemoi1.png" type="image/x-icon" />
