### ISSUE TITLE
Create basic template for front-end with Bulma

### ISSUE THREAD

**Issue by nobleburgundy** [nobleburgundy/weather-jamz#6]
Update index.html with Bulma integrated using the cdn...

https://bulma.io/documentation/overview/start/

**Comment by Kay0s** [comment]
![mockUp](https://user-images.githubusercontent.com/71153831/98303307-848de280-1f83-11eb-9897-be1de05b0b41.jpg)

**Comment by klyngdal** [comment]
looks like Kristina  pushed a basic html outline
