### ISSUE TITLE
Front-End Add need a ul element on html front end line 52

### ISSUE THREAD

**Issue by Kay0s** [nobleburgundy/weather-jamz#78]
https://github.com/nobleburgundy/weather-jamz/pull/75/commits/1f54e07e1bcda2b9cb03390d0950761befbd2127
…ed a ul element on html front end line 52

@Meechlouch thanks for the update. Can you please elaborate on what you need and where? I'll make sure it gets turned into an issue and I'll handle it.

**Comment by Meechlouch** [comment]
Actually, you can add it where ever you want it to display, just match the
id name historyList.

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/98872031-86501e00-243b-11eb-9e34-ce019159fca8.png)

Added div id="historyList"
ul id ="whistoryList"

The above will be in the same card where the current weather is shown:

<div id="display">
            <h1 class="nameTemp has-text-white"></h1>
            <p class="weatherDay has-text-white"></p>

This ul element will be added with the header update, once the logo approval vote is tallied.

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/98954526-7aa83a00-24c3-11eb-852c-3973889019d5.png)
added to index.html
