### ISSUE TITLE
Back-End add to on-click on submit remove hidden class from line 46 index.html (Play a Weather Jam(h4)

### ISSUE THREAD

**Issue by Kay0s** [nobleburgundy/weather-jamz#82]

**Comment by Kay0s** [comment]
Also remove hidden attribute to "Previous Search".

**Comment by nobleburgundy** [comment]
@Kay0s - what is this exactly? I think line 46 doesn't apply anymore since changes have occurred. Maybe just copy the code block here using the <> formatting button and we can take a look.

**Comment by Kay0s** [comment]
@nobleburgundy the text that originally was going to appear with the submit button press, now is viewable on load of page.  No need to add JavaScript code.
